name: Deploy Staging

on:
  pull_request:
    branches: [staging]
    types: [closed]

jobs:
  deploy-staging-heroku:
    name: Deploy Staging to Heroku
    if: >-
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Deploy to Heroku Staging
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
